### ISSUE TITLE
DRWN_DIRSEP not declared

### ISSUE THREAD

**Issue by canerhazirbas** [sgould/drwn#35]
I am using DARWIN latest release on Ubuntu 14.04.
When I link the library to my project, I get the following error:

Darwin/include/../src/lib/vision/drwnPatchMatch.h:392:30: error: 'DRWN_DIRSEP' was not declared in this scope.

**Comment by sgould** [comment]
You need to define __LINUX__ in your project Makefile. This can be done with the "-D__LINUX__" option to gcc.
