### ISSUE TITLE
mexImageCRF crashes

### ISSUE THREAD

**Issue by cslxiao** [sgould/drwn#41]
I use mexImageCRF for image with resolution of 1242x375, but it carshes without any observable rules. That is, for the same input it sometimes works well and sometimes crashes.
How could it happen?

My test environment is Ubuntu12.04 + Matlab R2012b.
Does anyone have the same problem?

**Comment by sgould** [comment]
This issue hasn't been reported before. Are you able to send me an example image and script that triggers the crash and I will look into it?

**Comment by cslxiao** [comment]
Thanks @sgould . I have sent you an email.
